//===-- StandaloneOps.td - Python bindings for gazprea --*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===---------------------------------------------------------------------===//

#ifndef PYTHON_BINDINGS_GAZPREA_OPS
#define PYTHON_BINDINGS_GAZPREA_OPS

include "Standalone/StandaloneOps.td"

#endif
